require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const pool = require('./db');

const app = express();
app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(express.static(path.join(__dirname, 'public')));

function auth(req, res, next) {
  const t = req.headers.authorization?.split(' ')[1];
  if (!t) return res.status(401).json({ error: 'Token manquant' });
  try { req.user = jwt.verify(t, process.env.JWT_SECRET); next(); } catch { res.status(401).json({ error: 'Token invalide' }); }
}
function admin(req, res, next) { if (req.user.role !== 'admin') return res.status(403).json({ error: 'Acces interdit' }); next(); }

app.post('/api/auth/register', async (req, res) => {
  try { const h = await bcrypt.hash(req.body.password, 10); const r = await pool.query('INSERT INTO profiles (email, password, nom, prenom, role) VALUES ($1,$2,$3,$4,$5) RETURNING *', [req.body.email, h, req.body.nom, req.body.prenom, 'etudiant']); const u = r.rows[0]; const t = jwt.sign({ id: u.id, email: u.email, role: u.role }, process.env.JWT_SECRET); res.json({ token: t, user: u }); } catch (e) { res.status(400).json({ error: e.message }); }
});
app.post('/api/auth/login', async (req, res) => {
  try { if (req.body.email === process.env.ADMIN_EMAIL && req.body.password === process.env.ADMIN_PASSWORD) { const t = jwt.sign({ id: 'admin', email: req.body.email, role: 'admin' }, process.env.JWT_SECRET); return res.json({ token: t, user: { id: 'admin', email: req.body.email, nom: 'Admin', prenom: '', role: 'admin' } }); } const r = await pool.query('SELECT * FROM profiles WHERE email = $1', [req.body.email]); const u = r.rows[0]; if (!u) return res.status(400).json({ error: 'Email incorrect' }); const m = await bcrypt.compare(req.body.password, u.password); if (!m) return res.status(400).json({ error: 'Mot de passe incorrect' }); const t = jwt.sign({ id: u.id, email: u.email, role: u.role }, process.env.JWT_SECRET); res.json({ token: t, user: { id: u.id, email: u.email, nom: u.nom, prenom: u.prenom, role: u.role } }); } catch (e) { res.status(500).json({ error: e.message }); }
});
app.get('/api/auth/me', auth, async (req, res) => { try { if (req.user.id === 'admin') return res.json({ id: 'admin', email: req.user.email, nom: 'Admin', prenom: '', role: 'admin' }); const r = await pool.query('SELECT id, email, nom, prenom, role FROM profiles WHERE id = $1', [req.user.id]); res.json(r.rows[0]); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/formations', async (req, res) => { try { const r = await pool.query('SELECT * FROM formations ORDER BY domaine, titre'); res.json(r.rows); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/formations/:id', async (req, res) => { try { const r = await pool.query('SELECT * FROM formations WHERE id = $1', [req.params.id]); res.json(r.rows[0]); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/formations/:id/cours', async (req, res) => { try { const r = await pool.query('SELECT * FROM cours WHERE formation_id = $1 ORDER BY ordre', [req.params.id]); res.json(r.rows); } catch (e) { res.status(500).json({ error: e.message }); } });
app.post('/api/inscriptions', auth, async (req, res) => { try { const r = await pool.query('INSERT INTO inscriptions (etudiant_id, formation_id, statut) VALUES ($1,$2,$3) RETURNING *', [req.user.id, req.body.formation_id, 'en_attente']); res.json(r.rows[0]); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/inscriptions/mine', auth, async (req, res) => { try { const r = await pool.query('SELECT i.*, f.titre as formation_titre FROM inscriptions i JOIN formations f ON i.formation_id = f.id WHERE i.etudiant_id = $1', [req.user.id]); res.json(r.rows); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/inscriptions/attente', auth, admin, async (req, res) => { try { const r = await pool.query("SELECT i.*, f.titre as formation_titre, p.nom, p.prenom, p.email FROM inscriptions i JOIN formations f ON i.formation_id = f.id JOIN profiles p ON i.etudiant_id = p.id WHERE i.statut = 'en_attente'"); res.json(r.rows); } catch (e) { res.status(500).json({ error: e.message }); } });
app.put('/api/inscriptions/:id/traiter', auth, admin, async (req, res) => { try { const r = await pool.query('UPDATE inscriptions SET statut = $1, date_traitement = NOW() WHERE id = $2 RETURNING *', [req.body.statut, req.params.id]); res.json(r.rows[0]); } catch (e) { res.status(500).json({ error: e.message }); } });
app.put('/api/progressions', auth, async (req, res) => { try { const r = await pool.query('INSERT INTO progressions (etudiant_id, formation_id, cours_id, statut, quiz_reussi, score_quiz) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (etudiant_id, formation_id, cours_id) DO UPDATE SET statut = $4, quiz_reussi = $5, score_quiz = $6 RETURNING *', [req.user.id, req.body.formation_id, req.body.cours_id, req.body.statut, req.body.quiz_reussi, req.body.score_quiz]); res.json(r.rows[0]); } catch (e) { res.status(500).json({ error: e.message }); } });
app.post('/api/examens', auth, async (req, res) => { try { const r = await pool.query('INSERT INTO resultats_examens (etudiant_id, formation_id, examen_id, score, reussi) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (etudiant_id, formation_id) DO UPDATE SET score = $4, reussi = $5 RETURNING *', [req.user.id, req.body.formation_id, 'examen_' + req.body.formation_id, req.body.score, req.body.reussi]); if (req.body.reussi) { const n = 'TW-' + Date.now() + '-' + Math.random().toString(36).substr(2, 6).toUpperCase(); await pool.query('INSERT INTO certificats (etudiant_id, formation_id, numero, score_final) VALUES ($1,$2,$3,$4) ON CONFLICT DO NOTHING', [req.user.id, req.body.formation_id, n, req.body.score]); } res.json(r.rows[0]); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/certificats', auth, async (req, res) => { try { const r = await pool.query('SELECT c.*, f.titre as formation_titre FROM certificats c JOIN formations f ON c.formation_id = f.id WHERE c.etudiant_id = $1', [req.user.id]); res.json(r.rows); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/notifications', auth, async (req, res) => { try { const r = await pool.query('SELECT * FROM notifications WHERE user_id = $1 ORDER BY created_at DESC', [req.user.id]); res.json(r.rows); } catch (e) { res.status(500).json({ error: e.message }); } });
app.put('/api/notifications/:id/lu', auth, async (req, res) => { try { await pool.query('UPDATE notifications SET lu = true WHERE id = $1', [req.params.id]); res.json({ ok: true }); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/admin/stats', auth, admin, async (req, res) => { try { const f = await pool.query('SELECT COUNT(*) FROM formations'); const e = await pool.query("SELECT COUNT(*) FROM profiles WHERE role = 'etudiant'"); const i = await pool.query("SELECT COUNT(*) FROM inscriptions WHERE statut = 'acceptee'"); const a = await pool.query("SELECT COUNT(*) FROM inscriptions WHERE statut = 'en_attente'"); const c = await pool.query('SELECT COUNT(*) FROM certificats'); res.json({ totalFormations: parseInt(f.rows[0].count), totalEtudiants: parseInt(e.rows[0].count), inscriptionsAcceptees: parseInt(i.rows[0].count), demandesAttente: parseInt(a.rows[0].count), certificatsDelivres: parseInt(c.rows[0].count) }); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/admin/certificats', auth, admin, async (req, res) => { try { const r = await pool.query('SELECT c.*, f.titre as formation_titre, p.nom, p.prenom FROM certificats c JOIN formations f ON c.formation_id = f.id JOIN profiles p ON c.etudiant_id = p.id'); res.json(r.rows); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/admin/etudiants', auth, admin, async (req, res) => { try { const r = await pool.query("SELECT p.id, p.nom, p.prenom, p.email, p.created_at, (SELECT COUNT(*) FROM inscriptions WHERE etudiant_id = p.id) as nb_inscriptions, (SELECT COUNT(*) FROM certificats WHERE etudiant_id = p.id) as nb_certificats FROM profiles p WHERE p.role = 'etudiant' ORDER BY p.created_at DESC"); res.json(r.rows); } catch (e) { res.status(500).json({ error: e.message }); } });
app.post('/api/admin/formations', auth, admin, async (req, res) => { try { const r = await pool.query('INSERT INTO formations (id, titre, description, domaine, image, duree, niveau) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (id) DO UPDATE SET titre=$2 RETURNING *', [req.body.id || ('f' + Date.now()), req.body.titre, req.body.description, req.body.domaine, req.body.image || '', req.body.duree || '50h', req.body.niveau || 'Debutant']); res.json(r.rows[0]); } catch (e) { res.status(500).json({ error: e.message }); } });
app.delete('/api/admin/formations/:id', auth, admin, async (req, res) => { try { await pool.query('DELETE FROM formations WHERE id = $1', [req.params.id]); res.json({ ok: true }); } catch (e) { res.status(500).json({ error: e.message }); } });
app.post('/api/admin/cours', auth, admin, async (req, res) => { try { const r = await pool.query('INSERT INTO cours (id, formation_id, titre, description, contenu, video_url, pdf_url, ordre, duree) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT (id) DO UPDATE SET titre=$3 RETURNING *', [req.body.id || ('c' + Date.now()), req.body.formation_id, req.body.titre, req.body.description || '', req.body.contenu || '', req.body.video_url || '', req.body.pdf_url || '', req.body.ordre, req.body.duree || '45min']); res.json(r.rows[0]); } catch (e) { res.status(500).json({ error: e.message }); } });
app.get('/api/admin/formations', auth, admin, async (req, res) => { try { const r = await pool.query('SELECT * FROM formations ORDER BY domaine, titre'); res.json(r.rows); } catch (e) { res.status(500).json({ error: e.message }); } });

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log('Tweadup port ' + PORT));
module.exports = app;
